AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true

Metrics/LineLength:
  Max: 100
  AllowURI: true

Metrics/ModuleLength:
  Exclude:
    - 'lib/fun_with_json_api/deserializer_class_methods.rb'

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Exclude:
    - 'spec/**/*_spec.rb'
