AllCops:
  TargetRubyVersion: 2.2

Metrics/LineLength:
  Max: 100
  AllowURI: true

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Exclude:
    - 'spec/fun_with_json_api/pre_deserializer_spec.rb'
