AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true

Metrics/LineLength:
  Max: 100
  AllowURI: true

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Exclude:
    - 'spec/**/*_spec.rb'
